// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/ankardo/CleanArch/internal/entity"
	"github.com/ankardo/CleanArch/internal/event"
	"github.com/ankardo/CleanArch/internal/infra/database"
	"github.com/ankardo/CleanArch/internal/infra/web"
	"github.com/ankardo/CleanArch/internal/usecase"
	"github.com/ankardo/CleanArch/pkg/events"
	"github.com/google/wire"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewFindOrderUseCase(db *sql.DB) *usecase.FindOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	findOrderUseCase := usecase.NewFindOrderUseCase(orderRepository)
	return findOrderUseCase
}

func NewFindAllOrdersUseCase(db *sql.DB) *usecase.FindAllOrdersUseCase {
	orderRepository := database.NewOrderRepository(db)
	findAllOrdersUseCase := usecase.NewFindAllOrdersUseCase(orderRepository)
	return findAllOrdersUseCase
}

func NewOrderCreateHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.OrderCreateHandler {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	orderCreateHandler := web.NewOrderCreateHandler(eventDispatcher, orderRepository, orderCreated)
	return orderCreateHandler
}

func NewFindAllOrdersHandler(db *sql.DB) *web.FindAllOrdersHandler {
	orderRepository := database.NewOrderRepository(db)
	findAllOrdersHandler := web.NewFindAllOrdersHandler(orderRepository)
	return findAllOrdersHandler
}

func NewFindOrderHandler(db *sql.DB) *web.FindOrderHandler {
	orderRepository := database.NewOrderRepository(db)
	findOrderHandler := web.NewFindOrderHandler(orderRepository)
	return findOrderHandler
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))
